// Durable-DAV Env shape for isolated package typechecks.
// Apps additionally include worker-configuration.d.ts (generated by
// `wrangler types`); bindings are `any` here so `env.DB` / `env.DAV_VOLUME` /
// `env.CRON_TASKS` are usable without @cloudflare/workers-types.
declare global {
  interface Env {
    DB: any;
    DAV_VOLUME: any;
    CRON_TASKS: any;
    CACHE?: any;
    DEBUG_MODE?: string;
    ENVIRONMENT?: string;
    DEV_AUTH_EMAIL?: string;
    DEMO_MODE?: string;
    DEMO_USER_EMAIL?: string;
    POLICY_AUD?: string;
    TEAM_DOMAIN?: string;
    SITE_URL?: string;
    MAX_VOLUMES_PER_USER?: string;
    MAX_CREDENTIALS_PER_VOLUME?: string;
    DEFAULT_CREDENTIAL_EXPIRY_DAYS?: string;
    MAX_CREDENTIAL_EXPIRY_DAYS?: string;
    MAX_FILE_BYTES?: string;
    DO_DEVICE_BYTES?: string;
    DAV_CACHE_TTL_SECONDS?: string;
    /**
    @deprecated Git-template leftover; `DAV_CACHE_TTL_SECONDS` wins when set.
    */
    GIT_CACHE_TTL_SECONDS?: string;
    /**
    Base64 of 32 bytes. Required to store a remote WebDAV target's credential:
    the Worker has to *present* that password on every sync, so unlike a bucket
    credential it cannot be a one-way hash. Absent means replications with a
    credential cannot be created, and the failure is reported rather than
    silently storing the secret in the clear.

    Superseded by `REPLICATION_ENCRYPTION_KEY_SECRET` (a Secrets Store binding),
    which is preferred everywhere and the only source used in production. This
    plain var remains for local dev and unit tests, where no Secrets Store is
    provisioned; `resolveReplicationKey` refuses it when
    `ENVIRONMENT=production`, so the two cannot silently trade places.
    */
    REPLICATION_ENCRYPTION_KEY?: string;
    /**
    `secrets_store_secrets` binding holding base64 of 32 bytes.
    */
    REPLICATION_ENCRYPTION_KEY_SECRET?: SecretsStoreSecret;
    REPLICATION_ALLOWED_HOSTS?: string;
    REPLICATION_SWEEP_LIMIT?: string;
    REPLICATION_SLICE_PATHS?: string;
    REPLICATION_SLICE_BYTES?: string;
    REPLICATION_SLICE_MS?: string;
    REPLICATION_PASS_MAX_MS?: string;
    REPLICATION_TIMEOUT_MS?: string;
    REPLICATION_HASH_ON_AMBIGUOUS?: string;
    MAX_REPLICATION_FAILURES?: string;
    MAX_REPLICATIONS_PER_VOLUME?: string;
  }

  type CloudflareEnv = Env;
}

export {};
